### ISSUE TITLE
Parsing table for KEGG and GO annotations

### ISSUE THREAD

**Issue by johanneswerner** [eggnogdb/eggnog-mapper#148]
Is there any parsing table I can use to map the annotations of KEGG, GO (and others that are available)? To have these annotations is very helpful, but I am wondering if there is an automatic way to map the IDs to the enzyme names/pathways. 

Thank you very much!

**Comment by Cantalapiedra** [comment]
Sorry for the delay answering.
And sorry, but I cannot further help much with this.
You will likely find scripts/repos addressing this need for the different databases.
If not, it should not be difficult to find the tables linking IDs with descriptions, so that you can just "join" the info of both tables.
