### ISSUE TITLE
Statistics of emapper results

### ISSUE THREAD

**Issue by MichWeb75** [eggnogdb/eggnog-mapper#217]
Dear developers,

this a wonderful software to get functional annotation for metatranscriptome data. I have successfully annotated approximately 2 GB of read data and I want to find out most overrepresented  GO / KEGG Terms. How do I proceed ?

1. Extract the GO-annotated sequences ?
`awk -F "\t" ' {if ($7) print $0}' eggnog.annotations > eggnog_annotations_GO.tsv`

2. Use a tool to perform command-line multiple Fisher-Exact Tests for each GO-Term ?
What would you use ?

Best, Michael

**Comment by Cantalapiedra** [comment]
Hi Michael,

there are different ways to perform enrichment analysis and many information sources out there. For example:
http://geneontology.org/docs/go-enrichment-analysis/

Note that to test enrichment you need to compare your annotated GOs against a background or reference, so that you can assess whether there is over- or under-representation in your data.

For example, if you wish to carry out a Fisher-Exact Test you can just load your data (and background) into R and run https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/fisher.test

You can also find other libraries, packages and tools. For example: https://bioconductor.org/packages/release/bioc/html/topGO.html

Good luck!

Best,
Carlos

**Comment by timregan** [comment]
Hi,

I'm especially interested in the KEGG outputs from Eggnog. These are often more useful than GO terms when dealing with non-model/uncharacterised species.
Do you know of any tools which can enrich for KEGG pathways (KID) from a set of genes, such as Eggnog output? Ideally taking hierarchical clustering into account?

Many thanks,
Tim

**Comment by Cantalapiedra** [comment]
Hi,

I am not sure to understand your question.
An alternative, using homology searches, could be the blast/ghost/kofamKOALA tools 
https://www.kegg.jp/blastkoala/

Best,
Carlos
