### ISSUE TITLE
Using a HMM profile as an input

### ISSUE THREAD

**Issue by fantin-mesny** [eggnogdb/eggnog-mapper#219]
Dear Eggnog team,

I have been using emapper.py a lot to annotate FASTA files. with the option ```-m diamond```.
Database files ```eggnog.db``` and  ```eggnog_proteins.dmnd``` are already in my data directory (downloaded using ```download_eggnog_data.py```).

Now, I would like to use eggnog-mapper to annotate protein families, using HMM profiles. If I understand correctly, this is possible using a command like this one:

```
python2 emapper.py -i input.hmm --qtype hmm -o output  -m hmmer 
```

I am however facing a few problems:
- I am asked to specify a database (bact, euk or arch).
When trying to specify one these options ('euk'), I get a ```ValueError: Database not found```:
``` Database euk not present. Use download_eggnog_database.py to fetch it ```
However, in the latest version of ```download_eggnog_data.py```, some lines are commented, making it impossible to download the 'euk' database. When I uncomment these lines, I get an HTTP error: file not found.
Moreover, I do not really want to specify one of these three kingdoms, and would like to keep them all.

- As eggnog-mapper relies on HMMER, I guess when the query is a HMM model, the ```dbtype``` has to be ```seqdb```. Therefore, I am not sure whether I should download some other data files or not. Can I just use the ```eggnog.db``` database ?

- I would not mind using both a HMM query and a HMM database, but I know it is not possible with HMMER. Can I download the TOTAL set of EggNog v5 HMMs somewhere ? I only find clade-specific files. 
With the total set of EggNog HMMs, I guess I could use another software like HMM-suite.

I hope everything is clear.
Thanks !

**Comment by Cantalapiedra** [comment]
Hello,

Current eggnog-mapper version 2 allows diamond searches only.
To be able to use hmmer mode you could try version 1. However, preliminary results suggest that we have almost to no improvement using hmmer instead of diamond. Moreover, for hmmer mode you need to specify a database, since an orthologous group, for a given gene, can be defined at different taxonomic levels. Therefore, I would recommend you using version 2 in diamond mode.

eggnog.db is not going to work as sequence DB for the search phase, since it is a sqlite database used for annotation phase. I would say that for the --usemem mode the --dbtype seqdb option is not available. It is likely that for the ondisk mode (not specifying --usemem) you could still use a fasta formatted file as --dbtype seqdb. Another option for this is using the hmm_mapper.py in the "refactor" branch, which will report just the HMM-sequence hits, but will perform no annotation. Also, you still would need to use the ondisk mode, or run "esl-reformat" on your fasta file, to be able to run HMM against sequence in --usemem mode.

I am not sure whether there is a total set of eggnog HMMs, maybe @jhcepas could shed some light on this. Not sure if the "NOG" database would represent the "root" level.

Best,
Carlos
