### ISSUE TITLE
emapper.seed_orthologs is not produced

### ISSUE THREAD

**Issue by nejcstopno** [eggnogdb/eggnog-mapper#256]
Hi @Cantalapiedra and @jhcepas

I am trying to make eggnog-mapper work on the HPCC but have some issues. 

Whenever I am using full datasets (multiple files of 1M sequences) (genes or proteins predicted by prodigal) the tool is not able to write out the emapper.seed_orthologs object. 

The error is following:
>subprocess.CalledProcessError: Command '/mnt/ufs18/rs-033/ShadeLab/Stopnisek/bean_metaG/SCRATCHcopy/megahit_all/combined_megahit_assembly/eggnogOutput/eggnog-mapper/bin/diamond blastp -d /mnt/research/ShadeLab/Stopnisek/bean_metaG/SCRATCHcopy/megahit_all/anvio/eggnog_proteins.dmnd -q /mnt/ufs18/rs-033/ShadeLab/Stopnisek/bean_metaG/SCRATCHcopy/megahit_all/combined_megahit_assembly/eggnogOutput/combined_megahit_assembly_proteins.part_001.faa --more-sensitive --threads 40 -e 0.001000 -o /mnt/ufs18/rs-033/ShadeLab/Stopnisek/bean_metaG/SCRATCHcopy/megahit_all/combined_megahit_assembly/eggnogOutput/emappertmp_dmdn_3sEq3F/5a9993f28c6841439d9e8847615c38f7 --top 3 --query-cover 0 --subject-cover 0' __returned non-zero exit status -9__

I tried installing the tool through conda and by cloning the repository but both times I have same issues (no results).

I am using following command
>for f in $OUT_DIR/*.faa; do
python $OUT_DIR/eggnog-mapper/emapper.py -m diamond --cpu 40 -i $f --output_dir $OUT_DIR/ --output fullAssembly --no_annot --no_file_comments -d ${DATABASE}/eggnog_proteins.dmnd --temp_dir $OUT_DIR/ --dmnd_db ${DATABASE}/eggnog_proteins.dmnd;
done

I next tested on a very small file containing only 100 sequences using the same exact command as above and this works fine, producing the object in less than a min.

>Total time = 53.801s
Reported 178 pairwise alignments, 178 HSPs.
73 queries aligned.
Done
   fullAssembly.emapper.seed_orthologs
Total time: 53.9921 secs

Any idea/suggestion how to solve this problem? I could potentially make subsets of a couple 100 sequences in each but this is not ideal. I tested if it would work with 500, 1k or 10k sequences in each but no luck. However it does with 100 and in a loop.

**Comment by Cantalapiedra** [comment]
Hi @nejcstopno ,

About the diamond error, you could try to run the diamond command itself, to see if it is able to finish. Because at first glance I cannot see what could be the source of the error. Something like:

eggnog-mapper/bin/diamond blastp -d eggnog_proteins.dmnd -q combined_megahit_assembly_proteins.part_001.faa --more-sensitive --threads 40 -e 0.001000 -o dmnd_test.part_001 --top 3 --query-cover 0 --subject-cover 0

Also, if you are not bound to any specific version I would recommend you cloning the version under the "refactor" branch, since it is far ahead in development than previous versions, and it is easier for us to help with, since it is the one more active.

I hope this makes sense. Please, report back with your thoughts please.

Best,
Carlos

**Comment by nejcstopno** [comment]
Hi @Cantalapiedra,
Thank you so much for your prompt reply. I ran the diamond by itself and it is killing it too. I will try to use scratch space and maybe filter out short reads (<1000bp) before.

**Comment by Cantalapiedra** [comment]
Could it be that some of your sequences contain something making it crash? Those sequences could be not there when you do the subsampling, and that would be the reason why with fewer sequences is not crashing at all. Just guessing
