### ISSUE TITLE
if i want to insert an independently run diamond blast output to emapper - what diamond blastp command should I use?

### ISSUE THREAD

**Issue by sapuizait** [eggnogdb/eggnog-mapper#258]
Assuming that I would like to run independently the diamond blastp and generate a similar output to the one emapper creates, what is the exact command that I should use?

I am asking because I have a ginormous dataset and i cannot run processes in parallel with emapper - but I can with diamond blast. That way I can first generate the seed files and then do the annotation using the emapper

I assume the command that I would have to run would look like this:
diamond blastp -k1 --more-sensitive -outfmt 6 qseqid sseqid evalue score --query ~/data/input/test.orfs --db eggnog_proteins.dmnd -p 32 --out sth.direct.diamond

correct?

**Comment by Cantalapiedra** [comment]
Hi @sapuizait ,

just out of curiosity, why you cannot run emapper in parallel?

Besides that, what diamond blastp command to run depends on what you want to achieve. We are not using -k 1, but --top 3 and then a postprocessing step to keep the first hit only. You could also perform some filterings at that stage, or use other diamond filtering thresholds, like -e, --subject-cover, --query-cover, etc. 

Moreover, --more-sensitive is a bit slow and I am not sure whether there is much gain on using it, unless you are using rather distant sequences as queries. In my opinion, you should be fine with --sensitive, although that depends on how ginormous is your dataset, of course. You could also leave the default (aka fast mode) depending on your data.

As probably you already know, the most important is that you create a seed_orthologs file to be used as input for the annotation step:

query TAB hit TAB evalue TAB score

I hope this makes sense.

Best,
Carlos

**Comment by sapuizait** [comment]
Thanks Carlos, it helps a lot - 
In functional annotation, i typically use an 1e-05 threshold
Well, regarding your question about running it in parallel, i am running it in a local cluster that does have lots of processors and RAM, however i have to compile it locally in my directory and i dont want to run a loop but instead lance at the same time a couple of hundred jobs at the same time.
Its just as far as I remember last time i tried to run emapper in parallel using the same script, it did not work - or maybe i did sth wrong and i should try again?

again, thanks,
P

**Comment by Cantalapiedra** [comment]
> Thanks Carlos, it helps a lot -

Glad to read that.

> In functional annotation, i typically use an 1e-05 threshold

OK. I guess you can use the diamond parameter or filter out later. Also, in current version of eggnog-mapper there is a --seed_ortholog_evalue parameter which can be use during the annotation step.

> Well, regarding your question about running it in parallel, i am running it in a local cluster that does have lots of processors and RAM, however i have to compile it locally in my directory and i dont want to run a loop but instead start at the same time a couple of hundred jobs at the same time.
> Its just as far as I remember last time i tried to run emapper in parallel using the same script, it did not work - or maybe i did sth wrong and i should try again?

OK thanks for the explanation. We usually launch many emapper tasks in the clusters we use (most often Slurm clusters), but maybe that depends on your SO, filesystem and cluster manager, and pipeline, scripts etc you are implementing as well.

> 
> again, thanks,
> P

Anytime.

Best,
Carlos

**Comment by sapuizait** [comment]
Thanks again for following up on this!
Regarding the cluster question, we use slurm here too! As far as I remember last time I tried to run an array by using 
`python2.7 emapper.py -i "${tab-array}" --cpu 16 --servermode --temp_dir "$temp" --output "$output"/"$shortname" -m diamond`
But it would not run more than 1 task - does each task require its own script, or did sth went very wrong?
Thanks,
P

**Comment by Cantalapiedra** [comment]
Hi @sapuizait ,

it is difficult to say why it was running only 1 task without checking the full script and the call to slurm, nor the emapper and slurm output and error.

We usually do something like:

`sbatch -a 1-${numfiles} -o slurm_out/%A_%a.out -e slurm_err/%A_%a.err emapper_slurm.sh input_files.list`

The `emapper_slurm.sh` script would use the `SLURM_ARRAY_TASK_ID` to retrieve the actual input file from `input_files.list`, and then run `emapper.py` as you did, except that the `--output` and/or `--output_dir` need to be a different one for each task, or `emapper.py` will complain that the output file already exists, and will certainly run only once. For example: `--output "$output"/"$shortname"_"$SLURM_ARRAY_TASK_ID"`

I am telling this by memory alone. Let me know if you need further help trying this.

Best,
Carlos

**Comment by sapuizait** [comment]
Hey Carlos

Thanks! Will give it a try!
P

**Comment by sapuizait** [comment]
Two last questions!
1. I saw in the tutorial that you suggest to merge all seed outputs of the diamond blast to one big file before the annotation step. 
Considering my dataset, I cannot do that or else the job would be running for months (possibly years). Is there any reason I couldnt annotate the individual files separately and then just `cat * > all.annotations`
2. What speeds up the process for the 2nd step (the annotations): is it RAM, processors, free space or having the db in the same partition where the queries are? I gave it a try yesterday and it was annotating 0.48q/s which is a bit disappointing...
Once again Many thanks,
P

**Comment by Cantalapiedra** [comment]
Hi,

1. Yes, you can do it everything separatedly.
2.  The annotation step is slow, specially when sqlite DB is first used, so that no results are cached at all. We are working to try to improve this, but as of now it is that slow yes. The main ideas I can think of to speed up the process is to parallelize as much as you can (I guess you are already doing this) and using the sqlite DB (the eggnog.db file) store in a non-NFS drive or, even better, copying the whole file to /dev/shm, which should make read access to the database faster. When I run this on slurm, I check whether the file is or not already in /dev/shm, so that I can copy for each node if not already present. Just remember to remove the database from all nodes once you have run all the jobs, better than removing it between jobs (I believe).

I hope this is of help.

Carlos

**Comment by sapuizait** [comment]
Thanks, I assume for the 2nd part (the annotation part), I only need the eggnog.db file and NOT the eggnog.proteins.dmnd file, correct?

**Comment by Cantalapiedra** [comment]
Yes, you only need the eggnog.db file for the annotation step.
Also, not completely sure, you could experience some speed gain as the queries are being processed and cached.
For example, you could compare the speed running a a few queries, then stop it and run the same queries again. If the cache works fine, the speed should raise significatively, which means that as more queries are processed will probably speed up things.

**Comment by sapuizait** [comment]
great, thanks! will try all that and see how it goes!

**Comment by Cantalapiedra** [comment]
Great, good luck!

I will close this just to organize myself. Feel free to reopen or ask anything you want.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Hi @sapuizait ,

I just implemented the option to load the sqlite DB into memory in the "refactor" branch, adding the flag `--dbmem`. 
I thought you could be interested on this, since you have large datasets.
I did a few tests, getting pretty cool rates:

 All queries processed. Time to perform queries:77.2264666557312 rate:54.71 q/s
 Processed queries:4225 total_time:161.8365478515625 rate:26.11 q/s

 All queries processed. Time to perform queries:68.677561044693 rate:61.52 q/s
 Processed queries:4225 total_time:152.83441066741943 rate:27.64 q/s

All queries processed. Time to perform queries:69.89936304092407 rate:60.44 q/s
 Processed queries:4225 total_time:162.90908908843994 rate:25.93 q/s

The "All queries..." lines show the time and rate to process each query, without including the time to load the DB.
The "Processed queries..." includes the time to load the DB both for the total time and the rate of queries per second.
Therefore, as more queries are added, you should be closer to the top rate (e.g. 54.71q/s) than to the bottom rate (e.g. 26.11 q/s).

In case you decide to give it a try, note that the DB takes up to 44GB to load into RAM, so depending on the mem you have in your nodes you may want to send only 1 job per node, or more... Therefore, it is important that you send as much sequences as possible to the same job, to take advantage of the DB loaded in memory and avoid loading it often.

Also, note however that the "refactor" branch is rather different to the "master" branch, and even the output format changes, so if you are bound to the previous format maybe you won't want to switch to the "refactor" branch. Check the wiki to have an idea of format, options, etc, although it is WIP and not completely updated: https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2-*refactor*

Best,
Carlos

**Comment by sapuizait** [comment]
Thanks a lot, that looks great, I ll surely try it and let you know how it goes
P

**Comment by sapuizait** [comment]
OK, turns out I may need some help running the refactor branch
Deployed the file in my directory in the local cluster and tried to run sth like 
`./emapper.py --annotate_hits_table ~/data/trash/test/xaa --servermode --dbmem --data_dir /storage/biodatabanks/db/eggNOG-mapper/embl_eggnog_emapperdb_2019-3-19/flat/ -m no_search --no_file_comments -o ~/data/trash/deletemeafteryoureadme`

where xaa is a test file with 2.5mil lines (just to see how far it gets)
but i keep getting the following error:

`File "./emapper.py", line 55
    help=f'Input FASTA file containing query sequences (proteins by default; see --translate). '                                                    ^
SyntaxError: invalid syntax`

funny thing if i also try ./emapper.py -- help - i get the exact same error

however, i need to specify, there is no python 3.7 in the cluster only 3.4.5 - but the master version runs fine with it... is python the problem?

thanks
P

**Comment by Cantalapiedra** [comment]
Hi,

yes, it seems it is complaining due to the f-strings, which are not available in version 3.4.5.
For the refactor version python 3.7 is required. I guess depending on your cluster this could be difficult to have. We usually use miniconda so that we can switch very easily between versions and environments.
Regarding biopython, if I recall correctly you would need it only if using CDS as input (--itype CDS or --translate).
In the case of psutil, you would need it if using the hmmer server mode (for example, when using `--pfam_realign denovo` , `-m hmmer --usemem`,  `hmm_server.py` or `hmm_worker.py`).

Besides that, you should not need the --servermode option.

Sorry for the inconveniences.

Best,
Carlos

**Comment by sapuizait** [comment]
Hey Carlos,

no worries, thanks a lot, in that case i only need the 3.7, then great i ll make a ticket to the admins and ask them if they can do sth about it
Again, thanks, that is very helpful

Cheers
P

**Comment by Cantalapiedra** [comment]
Hi,

Happy to try to help.

Just out of curiosity, couldn't you install Miniconda in your home folder?
Something like:

wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh

If your home folder is accessible from all the cluster, with a miniconda you may then install different python environments if you wish.

Also a question, was not emapper.py asking for the 3.7 version? I added recently to the scripts:

if sys.version_info < (3,7):
    sys.exit('Sorry, Python < 3.7 is not supported')

But if you didn't get the message then maybe it is not working at all.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Hi again...

Before running the emapper.py script you may need to download the DBs again, since there are differences also with the master version. For example, annotations now include pfam domains, and also NCBI taxa is now included without using ete3 modules.

Carlos

**Comment by sapuizait** [comment]
Hi again Carlos

before anything, thanks again for your continuous feedback, you ve been a huge help

your conda advice has been very helpful, i installed miniconda3 locally and even though I havent managed to activate my environment :D i was able to install python3.7 and and run it from the conda bin and start the emapper
`cd /envs/bin
./python3.7 /home/mydir/emapper.py  --annotate_hits_table /storage/scratch/mydir/2/input/merged.filtered.part-165.orfs.blastp --dbmem --data_dir /storage/biodatabanks/db/eggNOG-mapper/embl_eggnog_emapperdb_2019-3-19/flat/ -m no_search --no_file_comments -o /storage/scratch/mydir/2/output/merged.filtered.part-165.hits --cpu 32 --temp_dir /storage/scratch/mydir/2/tmp`

emapper starts normally loads the database but here is what I get:

`#  emapper-2.0.2
# emapper.py  --annotate_hits_table /storage/scratch/mydir/2/input/merged.filtered.part-165.orfs.blastp --dbmem --data_dir /storage/biodatabanks/db/eggNOG-mapper/embl_eggnog_emapperdb_2019-3-19/flat/ -m no_search --no_file_comments -o /storage/scratch/mydir/2/output/merged.filtered.part-165.hits --cpu 32 --temp_dir /storage/scratch/mydir/2/tmp
ESC[32mFunctional annotation of refined hits starts nowESC[0m
Loading source DB...
ESC[31mWarning: this can take a few minutes and load up to 45GB to RAM. Using --dbmem is recommended to annotate a large number of sequences.ESC[0m
Error: annotation went wrong for line "N36_k127_1237470_2       663278.Ethha_1188       4.6e-106        391.3". no such table: pfam`

why is it complaining about pfam?

**Comment by sapuizait** [comment]
please ignore the previous comment, it just needed to re-download the eggnog db - just downloaded run it and it is running as we speak - will let you know if it manages and how fast!

**Comment by sapuizait** [comment]
OK Carlos, here is the result
'All queries processed. Time to perform queries:7284.575104236603 rate:84.40 q/s
 Processed queries:614844 total_time:7611.733911514282 rate:80.78 q/s
Done'

on the second file similar speed

on the third file:
'All queries processed. Time to perform queries:5752.747357130051 rate:105.53 q/s
 Processed queries:607093 total_time:6144.693129777908 rate:98.80 q/s
Done'

speed seems to drop the bigger the file and the longer it runs but the speed is beyond my wildest expectations! Thanks a lot man, i ll make sure i ll mention u in the acknowledgements of whatever we publish out of this!

**Comment by Cantalapiedra** [comment]
Hi @sapuizait ,

I am glad you finally got it working and that is faster than before.
Thank you very much for your patience and for testing and reporting this! 
It would be awesome to be acknowledged jajaa but no need, really.

Any other question you may have will be welcome.

Best,
Carlos

**Comment by sapuizait** [comment]
small weird problem (which I think i can get around it but i ll mention it in case sb else faces it)
when i run some small files to test it (100k queries per file, 3 files), everything works perfectly 
when i run the actual files which are much bigger (10.5million queries), it seems to annotate just fine (according to the log) but then there is nothing in the output directory... 
`python3.7 /home/pasapoun/eggnog-mapper-2.0.4-rf1/emapper.py --annotate_hits_table $WORKDIR/input/"${tab[$SLURM_ARRAY_TASK_ID]}".orfs.blast --dbmem --data_dir /home/mydir/data/db -m no_search --no_file_comments -o ~/data/input/files/"${tab[$SLURM_ARRAY_TASK_ID]}".hits --cpu 32 --temp_dir $WORKDIR/tmp`
where $WORKDIR is /storage/scratch/$USER/$SLURM_ARRAY_TASK_ID
tried it twice and i ran into the same problem: no output files
will try 2 solutions: 1. send output to another directory `~/data/output` and 2. try to give as input smaller files 
any ideas why this may be happening?

Cheers and happy holidays
P

**Comment by Cantalapiedra** [comment]
Hi @sapuizait ,

sorry for the delay answering. I guess that the test you did with 100k queries is exactly the same as with 10.5M? I mean using --temp_dir, --dbmem, .. the same options. It could be a bug related with --temp_dir? I am not sure... Also, according to the log, did the job finished correctly? In some occasions, using Slurm we don't get the output until the job has finished completely. Another idea is whether the temp or final directory have enough room. I am just trying to figure out what happened because I have not this problem myself, although I am running jobs up to 1.6M queries, which is an order of magnitude smaller that yours.

Best,
Carlos

**Comment by sapuizait** [comment]
Hey @Cantalapiedra 

happy 2021!
not sure why it does that but it is really not a problem! I suspect it is a slurm related issue but didnt have the time to try to a local machine. In any case I have automated the process so the main query is split to 1mil files and it runs it beautifully.
The log does not show an error but what i noticed for the ones that do not produce an output is that their logs do not show the emapper msg that is usually displayed at the end of the annotation process. If nobody else has the issue I suspect it is my slurm

Cheers
P

**Comment by Cantalapiedra** [comment]
Hi,

happy 2021 too!
I have been thinking about this, and maybe it is due to storing too many annotations in a single list.
Maybe we should output chunks of annotations, maybe as a future enhancement.
Anyway, as it is unrelated to the original issue I will close this.

Feel free to re-open or re-issue to ask anything.

Best,
Carlos
