### ISSUE TITLE
Should I use cds sequence rather than unigene seq?

### ISSUE THREAD

**Issue by Lix1993** [eggnogdb/eggnog-mapper#269]
eggNOG-mapper website says it require `Up to 100,000 CDS/protein sequences in FASTA format`

I'm using eggnog-mapper v2  `emapper-2.0.1b-2-g816e190`  with `--translate  -m diamond`,  
I think this may use diamond blastx , which translate seq in 6 frame,  there is no need to  use cds seq.

Is this correct?

**Comment by Cantalapiedra** [comment]
Hi,

yes, in version 2.0.1b --translate will run diamond using the "blastx" mode.
Note however that the result may be different than what you would expect using "blastp" mode after translating a CDS, since the best hit could be a different one than the expected ORF (which could be an advantage in some situations).

Also, in the "refactor" version you can use also "--itype genome" or "--itype metagenome", along with "--genepred search" to run diamond in "blastx" mode, but obtaining more than one annotation if more than one blastx hit is found (i.e. treating the input sequence as a contig instead of as a CDS or transcript).

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Hi,

actually, I changed the behaviour in the last version.
When --itype CDS is used, diamond or mmseqs are run in "blastx" mode.
If --translate is used along --itype CDS, the CDS are actually translated to proteins, and diamond or mmseqs are run in "blastp" mode

Best,
Carlos

**Comment by Lix1993** [comment]
Thanks for  you reply.
