### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object with --pfam_realign realign

### ISSUE THREAD

**Issue by vragh** [eggnogdb/eggnog-mapper#301]
Hi `eggNOG` team,

Thank you for all the wonderful work on the database and the associated tools!!

I am attempting to run `emapper.py` on a protein `FASTA` file, and I've encountered the following error: `TypeError: cannot unpack non-iterable NoneType object`.

Here are the logs:

`stderr`:
```
Funcional annotation of hits...
0 1.6689300537109375e-06 0.00 q/s (% mem usage: 7.60, % mem avail: 92.38)
Traceback (most recent call last):
  File "/path/to/miniconda3/envs/eggnogmapper_conda/bin/emapper.py", line 662, in <module>
    n, elapsed_time = emapper.run(args, args.input, args.annotate_hits_table, args.cache_file)
  File "/path/to/miniconda3/envs/eggnogmapper_conda/lib/python3.9/site-packages/eggnogmapper/emapper.py", line 317, in run
    n, elapsed_time = self.run_generator(annotated_hits)
  File "/path/to/miniconda3/envs/eggnogmapper_conda/lib/python3.9/site-packages/eggnogmapper/emapper.py", line 255, in run_generator
    for item in generator:
  File "/path/to/miniconda3/envs/eggnogmapper_conda/lib/python3.9/site-packages/eggnogmapper/annotation/annotator.py", line 290, in unpack_annotations
    for (hit, annotation), skip in annots:
  File "/path/to/miniconda3/envs/eggnogmapper_conda/lib/python3.9/site-packages/eggnogmapper/annotation/output.py", line 28, in output_orthologs
    for ((hit, annotation), exists) in annots:
  File "/path/to/miniconda3/envs/eggnogmapper_conda/lib/python3.9/site-packages/eggnogmapper/annotation/output.py", line 146, in output_annotations
    for (hit, annotation), exists in annots:
  File "/path/to/miniconda3/envs/eggnogmapper_conda/lib/python3.9/site-packages/eggnogmapper/annotation/pfam/pfam_modes.py", line 48, in run_pfam_mode
    all_annotations, queries_pfams = load_all_annotations(annots_generator)
  File "/path/to/miniconda3/envs/eggnogmapper_conda/lib/python3.9/site-packages/eggnogmapper/annotation/pfam/pfam_modes.py", line 98, in load_all_annotations
    (query_name, best_hit_name, best_hit_evalue, best_hit_score,
TypeError: cannot unpack non-iterable NoneType object


```

`stdout`:
```
/path/to/miniconda3/envs/eggnogmapper_conda/bin/diamond blastp -d /path/to/eggnog_data/eggnog_proteins.dmnd -q /path/to/outputs/inputfile.fasta --threads 16 -o /path/to/outputs/eggnogmapper/outputdir/outputfile.emapper.hits  --ultra-sensitive -e 0.001 --top 3  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp
Re-aligning queries to PFAM domains from orthologs
```

And this was the command invocation:
```
#  emapper-2.1.2
# emapper.py  --output_dir /path/to/outputs/eggnogmapper/outputdir --output outputfile --go_evidence all --report_orthologs --tax_scope Metazoa --sensmode ultra-sensitive -m diamond --itype proteins --cpu 16 --pfam_realign realign --data_dir /path/to/eggnog_data -i /path/to/outputs/inputfile.fasta

```

I've obfuscated the paths here but they were all correct.

I presume it is `--pfam-realign realign` that is causing this error?

Your help would be much appreaciated.

**Edit:**
I have the tool installed via `conda`. This is what exists in the tool environment:
```
# packages in environment at /path/to/miniconda3/envs/eggnogmapper_conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
biopython                 1.78             py39h3811e60_2    conda-forge
boost-cpp                 1.74.0               hc6e9bd1_2    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py39hf3d152e_1    conda-forge
diamond                   2.0.9                hdcc8f71_0    bioconda
easel                     0.47                 h516909a_0    bioconda
eggnog-mapper             2.1.2              pyhdfd78af_0    bioconda
gawk                      5.1.0                h7f98852_0    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
hmmer                     3.3.2                h1b792b2_1    bioconda
icu                       68.1                 h58526e2_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                9_openblas    conda-forge
libcblas                  3.9.0                9_openblas    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgfortran-ng            9.3.0               hff62375_19    conda-forge
libgfortran5              9.3.0               hff62375_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
libidn2                   2.3.0                h516909a_0    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
libopenblas               0.3.15          pthreads_h8fe5266_0    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
libunistring              0.9.10               h14c3975_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
mmseqs2                   13.45111             h95f258a_1    bioconda
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.20.2           py39hdbf815f_0    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
pip                       21.1.1             pyhd8ed1ab_0    conda-forge
prodigal                  2.6.3                h779adbc_3    bioconda
psutil                    5.8.0            py39h3811e60_1    conda-forge
python                    3.9.2           hffdb5ce_0_cpython    conda-forge
python_abi                3.9                      1_cp39    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                49.6.0           py39hf3d152e_3    conda-forge
sqlite                    3.35.5               h74cdb3f_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
wget                      1.20.1               h22169c7_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge
```

**Comment by Cantalapiedra** [comment]
Hi @vragh ,

thank you for your kind words, and thank you for reporting the bug.

It is indeed an error when running `--pfam_realign realign|denovo`, I guess that for datasets of 100 queries and above, since it is failing when firing up the `hmmpgmd` servers from hmmer.
We are currently looking into it. The same code is used for `hmm_server.py` and `hmm_mapper.py`, which seem to be running fine. Hopefully, we can find a solution and fix it within the next few days. 

My suggestion, if you need to run your analyses asap, would be running `emapper.py` without `--pfam_realign`, and then trying with `hmm_server.py` and `hmm_mapper.py` to get the denovo pfam annotations.

I am aware that this is not the ideal situation, so sorry for the inconveniences.

Best,
Carlos

**Comment by vragh** [comment]
Hi @Cantalapiedra ,

Thank you for your prompt response!! I do hope that this issue gets resolved soon.

So if I were to invoke a run with `hmm_server.py` and `hmm_mapper.py` alongside, what would this look like? And how do I combine the results from these with those from `emapper.py`?

I would like to ask: do you even recommend running `--pfam_realign` portion at all? I had the feeling that your recommendation seems to be that the annotations via `diamond` are enough, but I am concerned that this would lead to a high false positive rate since my sequence set is a translated  _de novo_ transcriptome, and thus contains partial sequences within.

**Comment by Cantalapiedra** [comment]
Hi @vragh ,

> So if I were to invoke a run with `hmm_server.py` and `hmm_mapper.py` alongside, what would this look like? And how do I combine the results from these with those from `emapper.py`?

These are indeed good questions. When you run `emapper.py --pfam_realign realign|denovo` besides the PFAMs in the annotations file you obtain an additional file with PFAM positions. When you run `hmm_mapper.py` you get a file which is similar to the latter, with query, PFAM, positions, etc. The main difference is what you say: if you use `emapper.py` the PFAMs in the annotations file should be those in the additional file; when you run `hmm_mapper.py` the PFAMs in the annotations file are the ones transferred from orthologs and the ones in the additional file are the "denovo" ones. So yes, you may need to combine them if you need everything in a single file. You could do this more or less easily depending on your programming skills (e.g. with linux join, awk, python, etc).

> 
> I would like to ask: do you even recommend running `--pfam_realign` portion at all? I had the feeling that your recommendation seems to be that the annotations via `diamond` are enough, but I am concerned that this would lead to a high false positive rate since my sequence set is a translated _de novo_ transcriptome, and thus contains partial sequences within.

By default, every annotation term is transferred from the orthologs found within the Orthologous Group to the queries. That is why by default PFAMs are treated the same. In that sense, you could have both false positives and/or false negatives for your queries, depending on your alignment thresholds, taxonomic scope, etc. Also, it is faster running just the default mode, since it just transfers the PFAM IDs, whereas when realining (or denovo) you are now using hmmer to perform additional alignments. Those are the reasons why --pfam_realign options are not the default ones. Also, depending on what you want to do with the PFAM annotations in downstream analyses you may be OK with the transferred ones (e.g. enrichment), or you may need also positions of domains on your queries. In this latter case you also want to run --pfam_realign (or hmm_mapper.py) to have those positions.

I hope this makes sense.

Best,
Carlos

**Comment by vragh** [comment]
Hi @Cantalapiedra ,

Ah so if I'm just getting a nearly identical set of files (w.r.t. `emapper.py`), it's all good. I can just merge the outputs as you suggested.

And I think for my purposes (transcriptome annotation) I can afford to skip acquiring the domain positions on the sequences. I suppose I'll just go with the default options in the end.

**I'll leave the issue open since you remarked it is a bug.**

Thank you so much for your time and assistance here!!

**Comment by Cantalapiedra** [comment]
Thanks to you @vragh . I will use this issue to post a fix if we are able to figure it out.

**Comment by Cantalapiedra** [comment]
I finally found out that the bug was not the same as with `--pfam_realign denovo`.
`--pfam_realign realign` should be working fine now.

**Comment by vragh** [comment]
Hi @Cantalapiedra ,

Thank you for fixing this so fast!!

I can confirm that `--pfam_realign realign` works without hiccups now. I did not attempt `--pfam_realign denovo`, so can't comment on that. #303 seems to be referencing that issue as having been fixed, I suppose?

**Comment by Cantalapiedra** [comment]
Hi @vragh ,

thank you very much for testing and reporting this! It is of great help for us.

Best,
Carlos
