### ISSUE TITLE
Sequence too long (max 32000000 permitted)

### ISSUE THREAD

**Issue by Sher-Ojala** [eggnogdb/eggnog-mapper#322]
It appears my genome is too long for Prodigal.  Is there a work around?
Thank you!
Sher

code:
- Run gene prediction using a genome to train Prodigal

emapper.py -m mmseqs --itype genome --genepred prodigal -i /home/ragtag_output/scaffolds.fasta -o vug_test \
--training_genome None --training_file OUT_TRAIN_FILE

**Comment by Cantalapiedra** [comment]
Hi,

please, check this https://github.com/hyattpd/Prodigal/issues/54
We did not modified this parameter in eggnog-mapper.
You could install your own Prodigal with this parameter tuned and add it to your path, so that eggnog-mapper will use that one instead of the bundled one.
Another workaround would be to split your genome in several <=32Mbp fragments.

Best,
Carlos

**Comment by Sher-Ojala** [comment]
Carlos,

Thank you.  I had thought of those options, but I needed clarification on how to get the adjusted Prodigal working with eggnog-mapper, so this is helpful.

Best,
Sher

**Comment by Cantalapiedra** [comment]
Glad to help.
Good luck!
Please, reopen or reissue if you need to.
Best,
Carlos
