### ISSUE TITLE
One to Many Ortholog mapped to only one ortholog.

### ISSUE THREAD

**Issue by heineike02** [eggnogdb/eggnog-mapper#328]
I ran eggnog-mapper on the web and the out.emapper.orthologs file had a line which was labeled one2many, but seemed to only map to one gene.

 NC_036025.1:1089523-1090612(-)_1	one2many	Saccharomyces cerevisiae(4932)	*YJR153W

Is this a bug, or am I not correctly understanding what one2many means in this context?

**Comment by Cantalapiedra** [comment]
Hi @heineike02 ,

I would need further information about your emapper job.
Could you share with me the emapper job ID (MM_...) either here or to cpcantalapiedra@gmail.com?

Thank you.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Closing this.
Please, reopen or reissue if needed.

**Comment by Cantalapiedra** [comment]
Hi @heineike02 ,

I have yet not checked this.
I hope to be able to do it soon.
Thank you for reporting and for your patience.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Hi @heineike02 ,

In both cases, the wrong lines correspond to the seed ortholog.
The seed ortholog is included to have the complete list of orthologs for your query (when actually they are the orthologs of the seed). I guess it is not one2one nor one2many, because it is the seed, although it would make more sense to report it as one2one only? But in that case, the seed would be not reported when using --target_orthologs one2many. Maybe we should include as "seed orthologs" in all orthologs reports, without specifying one2one, one2many, etc in this particular case.

What are your thoughts on this?

From a practical point of view, just ignore the result which matches with the seed ortholog (that you can find in both .seed_orthologs and .annotations files), or just take into account that this is the seed and ignore the one2one, one2many, ... label.

I hope this is of help.

Best,
Carlos

**Comment by heineike02** [comment]
Hello Carlos,

Thanks so much for the detailed explanation - that helps a lot!

Best wishes,

Ben

**Comment by Cantalapiedra** [comment]
Thank you @heineike02 

Best,
Carlos
