### ISSUE TITLE
looking help for database download error

### ISSUE THREAD

**Issue by wwzzyy312** [eggnogdb/eggnog-mapper#375]
I am using the eggnog-mapper for the first time. For the database download, the 'download_eggnog_data.py euk bact arch viruses' script in the instructions was wrong. So, I tried '-h',  with the script 'python download_eggnog_data.py -H -d 2759', it runs, but when the 'Download HMMER database of tax ID 2759?' comes, with 'y' and default name, it showed 'The system could not find the specified path.'
How can I deal with it and get the proper Euk database? thank you!
![euk-wrong](https://user-images.githubusercontent.com/100649205/156541049-ee6e779f-4b54-4dc8-a94e-f6dbbaf29e1c.png)
![cmd-wrong](https://user-images.githubusercontent.com/100649205/156541067-6699450f-0393-413a-bf18-d6f39c72e9b2.png)

**Comment by Cantalapiedra** [comment]
Hi @wwzzyy312 ,

What OS are you using?

**Comment by wwzzyy312** [comment]
it is Window 10

**Comment by Cantalapiedra** [comment]
Hi @wwzzyy312 ,

We rarely use windows, so we don't test the scripts on it. Moreover, the scripts which are run by the eggnog-mapper download python script are bash scripts, which I am not sure if can be run within windows. 

You may use the ubuntu virtual machine (or any other linux virtual machine) within windows to be able to run linux software, or install a linux OS. Actually, if you plan to do work on bioinformatics I would recommend you to do it as soon as possible, since many tools are written/tests/run on linux.

Alternatively, although I would not recommend it, you could try to mimic the scripts to download the databases with windows code, but most likely you will have problems with further eggnog-mapper scripts.

I hope this is of help.

Best,
Carlos

**Comment by wwzzyy312** [comment]
Thank you so much for your advice! I'll study Linux OS soon.

**Comment by Cantalapiedra** [comment]
Glad to help.
Good luck with linux!
It is hard at the beginning, but is worth it (and can be fun xD).
I will close the issue. Re-open or re-issue if needed please.
Best,
Carlos
