### ISSUE TITLE
Gene age prediction based on orthologues group

### ISSUE THREAD

**Issue by rodrisenovilla** [eggnogdb/eggnog-mapper#402]
First of all, thanks for the great tool. I am a rookie at the field, but EggNOG is being really helpful so far, so thank you very much!

I have been using EggNOG for identifying the likely annotation of a non-model unannotated species, but in this case I would like to use the orthology groups and phylotypic trees to determine the gene age of their genes. When I saw the option, "max_annot_lvl", I thought that could be an equivalent to the age of the Most Recent Common Ancestor (MRCA), the most recent ancestral organism from which all equivalent genes are derived. So if a gene had max_annot_lvl = Vertebrata, that would be its age. 

However, I believe it is not as simple as that... So I would like to ask you if you know how other users, or yourselves, have used EggNOG or ETE toolkit for that purpose; and if you would recommend any additional methodology.

My question might be a little out of place, so thank you very much in advance!
Best,
Rodrigo

**Comment by Cantalapiedra** [comment]
Hi @rodrisenovilla ,

Thank you for your kind words about the tool :)

I am afraid that I have no experience with determining gene age. Maybe others could help with that. 
The `max_annot_lvl` field is not really a evolutionary concept, but just the tax level used to retrieve orthologs for annotation. Actually, this field is configurable by the user via `tax_scope` and `tax_scope_mode` fields.

If I understand what you were proposing, I guess that you could use the highest tax level of one OG. You could retrieve it from the `eggNOG_OGs` field. https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.8#orthologous-groups-fields

As I said, I am not expert on this, and as you said, I suspect that may be not so simple, there could be more accurate methods for this.

Sorry for not being of much help.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Hi @rodrisenovilla ,

I've been thinking more about this, and realized that you may not use the eggNOG_OGs field either, because it should always go up to root. To do what you suggested you may need to obtain the basal OG from eggNOG_OGs, retrieve all the proteins from such basal OG, and check the taxonomic scope which those proteins span. If they for example are only present in Metazoan, then you could guess that they are a metazoan synapomorphy (?). Sincerely, I don't know how eggnog-mapper current version could aid on this. Maybe the list of orthologs (if I recall correctly it is retrieved using `--report_orthologs`) may be of help. You could also retrieve data from the eggNOG website, and check if you could obtain the taxonomic scope of each OG from there.

Anyway, it could be a nice addition to future eggnog-mapper versions: reporting the widest(?) tax scope of the reported OG for each query... 

Thank you.

Best,
Carlos

**Comment by rodrisenovilla** [comment]
Thank you for your detailed reply! The widest tax scope might be a great addition for sure!
I will try to check if "report_orthologs" might be a good way to obtain the taxonomic scope... 
Thank you again,
Rodrigo
