### ISSUE TITLE
an empty output

### ISSUE THREAD

**Issue by zjq1011** [eggnogdb/eggnog-mapper#415]
Hello.
I ran the web version with all the default values of parameters.
The result was totally empty,
does that mean there were no hits found?  

![网页捕获_13-10-2022_124934_view officeapps live com](https://user-images.githubusercontent.com/101581813/195495147-5147110b-a74b-4be3-81ed-e4ecb844097b.jpeg)

**Comment by Cantalapiedra** [comment]
Hi @zjq1011 ,

Yes, it seems no hits were found. 
It is difficult to say if this is expected or due to some error without seeing your input data.
You could share some input data or the "MM_" identifier of your job so that I could check it.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Not sure if it is related to #417

**Comment by zjq1011** [comment]
Thank you for your reply.
I ran it again and got the same result,
so probably no hits were found.

Anyway, the id was MM_uaso9u59,
Do you mind checking it just in case?
Thanks in advance.

**Comment by Cantalapiedra** [comment]
Hi @zjq1011 ,

I checked the results and, unless I am overlooking something, they seem ok (though empty).

I also searched your first 3 proteins here http://eggnog5.embl.de/#/app/seqscan with no luck.

I don't know the nature of your proteins, but you could further try:
- Looking also for PFAM domains (under "Annotation options")
- You could also annotate SMART domains, but I warn you that it is rather slow.
- Changing the search filter options (under "Search filters"). 
- You may also try to look into the "novel families" instead of into eggnog5 proteins (under "Database"). 
- Another option is using the command line eggnog-mapper tool to change the sensitivity of the search (with diamond and mmseqs2 it can be increased a lot, or you could even use hmmer).

I hope this is of help.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Also #418 . This has to be something going wrong with the server. I will check again and report back.

**Comment by Cantalapiedra** [comment]
I ran again your job, because I thought that it was related with #417, and therefore it could have been some temporary error from the server. Also, for #418 re-running the job seems to have worked fine. However, the re-run of your job yielded 0 hits once more: http://eggnog-mapper.embl.de/job_status?jobname=MM_e4oipkqf

**Comment by zjq1011** [comment]
Thank you very much.
Unfortunately, I can not access http://eggnog-mapper.embl.de/ at the moment.
Last night it was ok, though.
Maybe I will wait for some time and try your advice.

By the way, are these options

> Looking also for PFAM domains (under "Annotation options")
You could also annotate SMART domains, but I warn you that it is rather slow.
Changing the search filter options (under "Search filters").
You may also try to look into the "novel families" instead of into eggnog5 proteins (under "Database").
Another option is using the command line eggnog-mapper tool to change the sensitivity of the search (with diamond and mmseqs2 it can be increased a lot, or you could even use hmmer).

available on the web service or only the stand-alone version?

**Comment by Cantalapiedra** [comment]
Glad to try to help.
It was not responding the web again? It seems to be working for me now.

All those options are both in the web and in the stand alone version.
The sections I pointed out (e.g. "Annotation options") are in the web.

**Comment by zjq101** [comment]
Thank you for your reply.
It works now, probably the Internet in my dorm was not so good.

I tried some new parameters, such as search filters, "novel families"
and "perform SMART domains", but no hits again.
I guess the reason will be the database itself.

What I can say about the inputs is that 
they are actually from a virus with little information known about its proteomics.
I am not so surprised about the result.

Thank you again for your kind help.
As for the result, I think it is not worthwhile to repeat it.
But I will appreciate it if you could check it (MM_n4mfhk0j)
to see whether the changes in parameters will correctly increase the sensitivity.

**Comment by Cantalapiedra** [comment]
Hi @zjq101 ,

Being that the nature of your data I guess it is expected that the novel families are not adding something useful.

However, I see that you actually obtained SMART results:

http://eggnog-mapper.embl.de/MM_n4mfhk0j/out.emapper.smart.out

You may try also with PFAM de novo. I say specifically "de novo", since "realignment" will not work, given that your queries were not annotated with any PFAM to begin with.

If you could run the emapper.py stand alone version, or just diamond, you may try with increased sensititivy.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
I ran emapper.py with your data using `--sensmode ultra-sensitive` and I got no hits from diamond, so I guess that the eggNOG DB is not including homologs to your sequences. I hope that you find some clues among the SMART/PFAM results.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
I am closing this issue.
Please, re-open if needed.
