### ISSUE TITLE
questions about the command line to annotate CDS and the "emapper.annotations" output file

### ISSUE THREAD

**Issue by AnaMariaCabello** [eggnogdb/eggnog-mapper#421]
Hi!
I'm using eggnog to annotate ORFs from metagenomic samples that I previously predicted with PRODIGAL. It's my first time working with functional annotations and I have some beginner questions:

**Q1.** I used this command line: emapper.py --cpu 32 -i ORF_prodigal.fasta --itype CDS  --output genecatalog --output_dir temp_data
and it worked, but, since my fasta file is "nucleotide" I hesitate whether I should have use also the --translate option together with the  --itype CDS option.

**Q2.** Regarding the emapper.annotation output file (I'm attaching an excel file as example): 
    **2.1.** In the "eggNOG_OGs" column,  what is the code after the tax id number? For instance in this annotation, what are 1MW0Z and 2UR5H codes referred to?
    COG0436@1|root,COG0436@2|Bacteria,1MW0Z@1224|Proteobacteria,2UR5H@28211|Alphaproteobacteria
    **2.2** I got codes in this column that corresponded to viruses; for instance (4QAKZ):
    4QAKZ@10239|Viruses,4QPYH@28883|Caudovirales,4QIM4@10662|Myoviridae
    Where does this code comes from? is it a unique code for viruses?
    **2.3** I got also KOGs (for eukaryotes) but the first code that appears is a COG, for example:
   COG2801@1|root,KOG0017@2759|Eukaryota,2XEDA@2836|Bacillariophyta
   How should I interpret this result? I'm interested in the functional annotation of prokaryotic genes from metagenomes (and build functional abundance tables), so I'm wondering whether I should filter out these annotations (and also the virus related ones) for downstream analyses. To predict ORFs I used PRODIGAL with default options (it uses archaea and bacteria genetic codes). Do we assume that PRODIGAL prediction of ORFs is only predicting archaea and bacterial genes?
    
**Q3.** My last question is about PFAMs annotations column. Is there a way to retrieve PFAM codes (i.e. PF02932) apart from the PFAM short names?

Thanks a lot, 
Ana
[prueba.emapper.annotation.xlsx](https://github.com/eggnogdb/eggnog-mapper/files/9844262/prueba.emapper.annotation.xlsx)

**Comment by Cantalapiedra** [comment]
> Hi! I'm using eggnog to annotate ORFs from metagenomic samples that I previously predicted with PRODIGAL. It's my first time working with functional annotations and I have some beginner questions:

Hi @AnaMariaCabello ,

> 
> **Q1.** I used this command line: emapper.py --cpu 32 -i ORF_prodigal.fasta --itype CDS --output genecatalog --output_dir temp_data and it worked, but, since my fasta file is "nucleotide" I hesitate whether I should have use also the --translate option together with the --itype CDS option.
> 

Yes, usually you want to use the `--translate` option along with `--itype CDS`. The main difference for your command (which is using `-m diamond` as default, is that when you don't use the `--translate` option, diamond will run in blastx mode, whereas if you use the `--translate` option, the CDS will be previously translated to proteins, and diamond will run in blastp mode. Check this:

https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.8#input-data-options

> **Q2.** Regarding the emapper.annotation output file (I'm attaching an excel file as example): **2.1.** In the "eggNOG_OGs" column, what is the code after the tax id number? For instance in this annotation, what are 1MW0Z and 2UR5H codes referred to? COG0436@1|root,COG0436@2|Bacteria,1MW0Z@1224|Proteobacteria,2UR5H@28211|Alphaproteobacteria 

Those codes correspond to the OG (Orthologous Group). Please check:

https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.8#orthologous-groups-fields

> **2.2** I got codes in this column that corresponded to viruses; for instance (4QAKZ): 4QAKZ@10239|Viruses,4QPYH@28883|Caudovirales,4QIM4@10662|Myoviridae Where does this code comes from? is it a unique code for viruses? 

I guess is the same answer as for 2.1. It is just the OG of those viral proteins.

>**2.3** I got also KOGs (for eukaryotes) but the first code that appears is a COG, for example: COG2801@1|root,KOG0017@2759|Eukaryota,2XEDA@2836|Bacillariophyta How should I interpret this result? I'm interested in the functional annotation of prokaryotic genes from metagenomes (and build functional abundance tables), so I'm wondering whether I should filter out these annotations (and also the virus related ones) for downstream analyses. To predict ORFs I used PRODIGAL with default options (it uses archaea and bacteria genetic codes). Do we assume that PRODIGAL prediction of ORFs is only predicting archaea and bacterial genes?
> 

I guess that Prodigal will just detect ORFs, which may include eukaryotic exons. 

> **Q3.** My last question is about PFAMs annotations column. Is there a way to retrieve PFAM codes (i.e. PF02932) apart from the PFAM short names?
> 

I am afraid that eggNOG-mapper does not provide the conversion of PFAM short names to codes. You may need to download the PFAM database, use the web API (not sure what is the state of this now, since they migrated to interpro), and/or use some tool for that.

> Thanks a lot, Ana [prueba.emapper.annotation.xlsx](https://github.com/eggnogdb/eggnog-mapper/files/9844262/prueba.emapper.annotation.xlsx)

Thank you.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Currently it seems you can search short names using: http://pfam.xfam.org/family/P53_tetramer
But this is currently redirecting to interpro and I guess this links will be removed by 2023.

**Comment by AnaMariaCabello** [comment]
Dear Carlos,
Thank you so much for all the clarifications. I'm sorry I missed the wiki page where most of this questions are properly answered.
Best,
Ana

**Comment by Cantalapiedra** [comment]
Hi @AnaMariaCabello ,

No worries. The wiki is maybe not so visible as it should be. Don't hesitate to ask anything you need.

Also, note that the field with OGs, tax IDs, etc is important information, because eggNOG-mapper uses the eggNOG database as reference. Let's say is intermediate information showing the results of querying the DB. That being said, it is not so important regarding functional annotation itself, where you want to focus on descriptions, functional ontologies, kegg, pfam, etc.

Best,
Carlos

**Comment by AnaMariaCabello** [comment]
Ok Carlos, I see, thanks for the tips and for being so reachable!

**Comment by Cantalapiedra** [comment]
I am closing this issue.
Please, re-open if needed.
