### ISSUE TITLE
EggNOG5.0 and e-mapper output different.

### ISSUE THREAD

**Issue by FabianRup** [eggnogdb/eggnog-mapper#429]
Dear EggNOG team, 

I am trying to annotate a non-model organism proteome with e-mapper. This works fine, however I noticed some substantial differences between previous e-mapper runs (> 1 Jahr ago) and the recent one in default mode. Even more, I realised that proteins that got *some* annotation before but not in the recent run are annotated when running them individually using EggNOG 5.0 sequence search. 
Do you have an idea why e-mapper would not annotate the proteins while EggNOG would?

Thanks for your help!
Fabian

**Comment by FabianRup** [comment]
Also, here are two example sequences:

>c85791_g1_i1_m.10071
VTNAQQPGPYTVKVSNVNKNTMAPFFTGNSPLGVLVFTDASVGTTIANITALDYDPAPDG
TVRYALLGGTGYGYFKVNDSTGAVTTNFNLTAFGQTNLVLVVAARDSGLYPMQSTRNVTL
VLANSTNTKPFFTTPVTTAGVPEGPASVGSVVTMVAAYTSDSVD

>c85792_g1_i1_m.10072
GVNYATLQVHGMLGNDPIDFLVDSGAAVSVVTNDILPTSVRTRIIREAPHTVGANGSALD
VLGRLEIPITLGQFCASHEFVVVRHLTVQCLLGMDFLNRYGAVIDCVKNTLSLLNPLPLE
SKRNVPTIVSNVTISETVEIPARSKMLIG

**Comment by Cantalapiedra** [comment]
Hi Fabian,

It is difficult to me to say why without knowing the versions and seeing some results with those sequences.
Note that some parameters related to the searches could have changed between versions, including the sensibility of the search algorithm etc.

I searched your sequences here http://eggnog5.embl.de/#/app/seqscan and I got some results. What are the results you obtain from eggnog-mapper? Are there search results but no annotations? Or you don't get even search hits.

Best,
Carlos

**Comment by FabianRup** [comment]
Hey Carlos, 

thank you so much for your answer. Yes, searching those exemplary sequences using the EggNOG sequence search gives (the expected) results. However eggnog-mapper does not even return any search hits. Are the default parameters from eggnog-mapper that different from the EggNOG sequence search?

Thanks and all the best
Fabian

**Comment by Cantalapiedra** [comment]
Hi Fabian,

Actually, the eggNOG sequence search and the eggnog-mapper search are very different, since the first one focuses on obtaining results for one query as fast as possible, and the second focuses on larger input datasets.

Your input sequences produce relatively high e-value/low score in eggnog5 web (which if I am not mistaken is using hmmer). Maybe eggnog-mapper (which uses diamond by default) is not able to find those hits. You may change diamond's sensibility parameters (--sensmode more-sensitive, for instance), the results filtering thresholds or even the aligner, to use hmmer instead.

Take a look at:

https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.8#Search_Options

Best,
Carlos

**Comment by FabianRup** [comment]
Hey Carlos, 

I see, thank you for the clarification! I will try different options and see what combination might be best for my dataset. 

Thank you!
Best
Fabian
