### ISSUE TITLE
emapper running forever

### ISSUE THREAD

**Issue by rsiani** [eggnogdb/eggnog-mapper#473]
Hi, 
I am annotating a bacterial genome using 
emapper-2.1.10 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: 5.0.2 / Diamond version found: diamond version 2.0.12 / MMseqs2 version found: 13.45111

I am running the program as follow (0 results in 64 CPUs):
emapper.py  --cpu 0 -i LR140.fa --itype genome --genepred prodigal -m diamond --trans_table 11 --dmnd_iterate yes --tax_scope none --tax_scope_mode Bacteria --go_evidence all --pfam_realign 
denovo --output LR140 --decorate_gff yes

The program is now running for 24 hrs with only intermediary files being produced. Is this a known bug? I know it's not the latest version, but I also tried uploading the genome to the web-server and it has been running for approximately the same time...

**Comment by Cantalapiedra** [comment]
Hi @rsiani ,

Did it finish finally? If not, does the output tell you something about which stage is running/stuck on?
You could also share the job ID (MM_xxxxxx) from the web version, to check it.

Best,
Carlos

**Comment by rsiani** [comment]
Hi @Cantalapiedra,
unfortunately it didn't, so I ended up falling back on another software. The jobs id are MM_xb4jbx7z, MM_yeh26e7i, MM_z2w9mt3r. I am starting to think there must be something wrong with the fasta format of these genomes, as I am also unable to complete jobs locally.. I once annotated a genome from the same collection using emapper, but that must have been at least 2 years of releases ago...

Best, 
Rob

**Comment by Cantalapiedra** [comment]
Hi @rsiani ,

I was able to run fine an analysis of your fasta file from  MM_xb4jbx7z using the command line (v2.1.12). Just a simple command, without pfam realign:

`mkdir test01; emapper.py --genepred prodigal -i queries.raw --itype genome -o out --output_dir test01 --cpu 8`

Regarding the web, I have seen that there are problems for your jobs to begin. It seems something related with the account which is created associated to your email. I will research further and write back if I find the cause.

Sorry for the inconveniences.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
It seems that the account which is associated to you in emapper web is a different one than the one you specified in the new submitted jobs. I edited your email in your info.txt file (http://eggnog-mapper.embl.de/MM_xb4jbx7z/) and now it seems to be running fine (http://eggnog-mapper.embl.de/job_status?jobname=MM_xb4jbx7z). 

Note that the issue preventing you from using another email account is actually a weird (to me) slurm issue (slurm is the cluster manager we use behind the scenes), in which not the whole email name is used to check whether an account already exists, but only a fragment from the beginning. Therefore, as your different emails all start the same (with your name @ something similar from your institute), they are detected as non existing but when the new account is going to be created they are detected as being the same ... weird issue, but I cannot solve it so far.

So my advice would be that you use always the same email if you finally decide to keep using eggnog-mapper.

Best,
Carlos

**Comment by rsiani** [comment]
I am curious why the pfam realignment would take so long, but good that there is a workaround.

Regarding the web version, now I get it. I had used the platform in the past, but after a hacker accident at my center, we were all changed to a different but similar one (the part before the @ doesn't change)

Thanks for checking again. I will close the issue then.

All the best, Rob

**Comment by Cantalapiedra** [comment]
Hi Rob,

The PFAM realignment is realigning each of your ORFs against the whole PFAM database using HMMER. That is why it can take some time to complete. However, there are ways to accelerate this using eggnog-mapper, and we use it to annotate millions of proteins sometimes. Actually, for the number of proteins predicted by Prodigal for your MM_xb4jbx7z job (>4,000) it should be relatively fast, since it should load the PFAM database into memory. However, hmmpgmd (the HMMER script used to load the DB into memory) does not always work properly, depending on HMMER version and OS, and/or factors which I don't know exactly yet xD sorry. You could actually check this using `hmm_mapper.py`, which is a script included with eggnog-mapper. Note that in the web the PFAM realignment is usually rather fast also, being the SMART annotation the one which can take veeery long to finish.

Also, if it was the PFAM realignment which was stuck, you should see `De novo scan of PFAM domains` in your emapper's output. If you don't see that, and you see `Functional annotation of hits...` then it is slow/stuck on the annotation stage, which is actually the slowest stage of eggnog-mapper, unless you use `--dbmem` (you need at least ~44GB RAM to use it), which makes it very fast in comparison.

I did another test with your data, using `mkdir test01; emapper.py --genepred prodigal -i queries.raw --itype genome -o out --output_dir test01 --cpu 8 --pfam_realign denovo --override`, and it took:

```
Total hits processed: 4558
Total time: 1105 secs
```

(although as it is a rerun, the annotation process is faster due to being cached. Nonetheless, it is clear that the PFAM realignments takes less than ~15 mins).

Regarding the change in your email, I will remove your previous email from the accounts, and hopefully in this way you may submit jobs again. Now that you mention, I think there was at least another colleague of you with the same change of domain, from muenchen to munich, or similar.

Best,
Carlos
