### ISSUE TITLE
download_eggnog_data.py -M EOS error

### ISSUE THREAD

**Issue by andymuan** [eggnogdb/eggnog-mapper#500]
Hi there, 

I am running eggNOG 2.1.7, before I run emapper.py with the -m mmseqs flag, I am running `download_eggnog_data.py -M ` to download the mmseqs database. I'm running into an EOS error below: 

> ESC[1;33mDownload main annotation database?ESC[0m [y,n] Traceback (most recent call last):
>   File "/usr/local/bin/download_eggnog_data.py", line 226, in <module>
>     if args.allyes or ask("Download main annotation database?") == 'y':
>   File "/usr/local/lib/python3.10/site-packages/eggnogmapper/utils.py", line 195, in ask
>     v = input("%s [%s] " % (string,','.join(valid_values) ))
> EOFError: EOF when reading a line

download_eggnog_data.py seems to run fine by itself. 

Thanks for your help!

**Comment by V-Varga** [comment]
Hello! @andymuan I realize I'm seeing your question a bit late, so you may have already solved it, but I thought I would leave a note in case anyone else encounters this same issue. 

I encountered this problem while trying to build EggNOG in a container. I was able to solve it by adding the `-y` flag to my command. Basically, the eggnog-mapper expects you to be able to interact on the command line in response to requests for permission to install each of the various databases. If you install using some automated system (like building a container, in my case), you have to specify the `-y` flag to answer "yes" to all permissions the program asks for, otherwise it will raise an error and exit.
(I'm not an EggNOG team member, so please take my comments with a grain of salt, but I hope this helps you!)

**Comment by Cantalapiedra** [comment]
Thank you @V-Varga for answering this.
Please, @andymuan , if the previous answer didn't solve your issue, don't hesitate to re-issue.
Best,
Carlos
