### ISSUE TITLE
Eggnog mapper web server is not working

### ISSUE THREAD

**Issue by ahmaduaf** [eggnogdb/eggnog-mapper#506]
Hi,

I am trying to open http://eggnog-mapper.embl.de/. However, the website is not working for the last few days.

**Comment by yvonnelee1988** [comment]
Hi, I got the same issue which says "502 Bad Gateway". 
We would greatly appreciate the developer's help in solving this issue!

**Comment by linruoran1999** [comment]
Is the problem solved? I'm plagued by the same thing.

**Comment by Pascalinesalvado** [comment]
Same problem

**Comment by linruoran1999** [comment]
I'm in too much of a hurry, installing the local version has taken up 22G of my nowhere-to-find space, but to no avail!

**Comment by zadavcvsv** [comment]
same

**Comment by AlexdeMendoza** [comment]
Is there any plan to recover the emapper web server? As some users commented here, downloading the package locally is not very efficient.

**Comment by yvonnelee1988** [comment]
Re: [AlexdeMendoza]
Echoing this.. I'm using Mac M1 and emapper cannot be used probably due to diamond doesn't work for M1.  So I managed to set up emapper on a Windows computer with a Linux VM... but the search had been slow and so far wasn't able to get an output yet...

**Comment by linruoran1999** [comment]
I'm trying to use the local version, but the ERROR message during data analysis of the local version says: insufficient space

**Comment by Cantalapiedra** [comment]
Hi everyone,

Thank you very much for reporting this. The servers hosting eggNOG-mapper web were down several days due to some problems which needed to be fixed.

Currently, the servers seem to be working again, and therefore we fired up the eggNOG-mapper web service, so that it should be running now.

It is likely that you will receive emails regarding previous jobs (done or failed).

Please, if you encounter any issue when running eggNOG-mapper web, let us know (here, as a new issue if nobody already reported the same) so that we can try to fix them as soon as possible.

Thank you very much, and sorry for the inconveniences.

Best,
Carlos

**Comment by ahmaduaf** [comment]
Thanks a lot. The server is accessible now. However, for some reason, after submission of the job no email is being received to start the job.

**Comment by Cantalapiedra** [comment]
Yes, you are right. We are trying to fix the issue with the emails. Thank you!

**Comment by tyhou** [comment]
Same problem here!

**Comment by Cantalapiedra** [comment]
> Same problem here!

Follow issue #511 for updates

**Comment by Andy326726** [comment]
I am sorry for that  but i can not open the online website. It said 502 error ,could you please help me to sovle the problem?

**Comment by ying6982** [comment]
> I am sorry for that but i can not open the online website. It said 502 error ,could you please help me to sovle the problem?

the same problem
